name = "tech-news-channel"
main = "worker.js"
compatibility_date = "2026-09-26"

[[d1_databases]]
binding = "DB"
database_name = "techpulse-db"
database_id = "659777d6-de82-4431-9cf9-c99857eb1bde"

[triggers]
crons = [ "0 * * * *" ]
