name = "techpulse-news-engine"
main = "worker.js"
compatibility_date = "2026-09-26"

[[d1_databases]]
binding = "DB"
database_name = "techpulse-db"
database_id = "14b321b7-f3f9-494d-ae96-e7def53e1358"

[triggers]
crons = [ "30 11 * * *", "0 19 * * *" ]
