const WORKER_URL="https://tech-news-channel.rahulsocialwits.workers.dev";
const sources=[["TechCrunch","https://techcrunch.com/feed/"],["The Verge","https://www.theverge.com/rss/index.xml"],["Ars Technica","https://feeds.arstechnica.com/arstechnica/index"],["WIRED","https://www.wired.com/feed/rss"],["Engadget","https://www.engadget.com/rss.xml"],["VentureBeat","https://venturebeat.com/feed/"],["Tom's Hardware","https://www.tomshardware.com/feeds/all"],["Android Authority","https://www.androidauthority.com/feed/"],["9to5Google","https://9to5google.com/feed/"]];

function token(){return sessionStorage.getItem("techpulse_admin_session")||""}
async function api(path,options={}){const headers={...(options.headers||{}),"Content-Type":"application/json"};if(token())headers.Authorization="Bearer "+token();const r=await fetch(WORKER_URL+path,{...options,headers});let data={};try{data=await r.json()}catch(e){}if(!r.ok)throw new Error(data.error||"Request failed");return data}
function showLogin(show){document.getElementById("loginGate").hidden=!show;document.getElementById("adminApp").hidden=show}
async function checkAuth(){if(!token()){showLogin(true);return false}try{await api("/admin/me");showLogin(false);return true}catch(e){sessionStorage.removeItem("techpulse_admin_session");showLogin(true);return false}}
function renderSources(){document.getElementById("sourcesList").innerHTML=sources.map(s=>'<div class="source"><b>● '+s[0]+'</b><small>'+s[1]+'</small></div>').join("")}
async function loadStats(){try{const data=await api("/admin/stats");const el=document.querySelector("#subscribers .empty");if(el)el.innerHTML="👥<b>"+data.subscribers+" active subscribers</b><span>Subscriber database is connected privately to Cloudflare D1.</span>"}catch(e){}}
async function loadPublished(){try{const r=await fetch("../data/articles.json",{cache:"no-store"});const data=await r.json();document.getElementById("total").textContent=data.length;document.getElementById("publishedList").innerHTML=data.map(x=>'<div class="item"><small>'+x.date+' · '+x.category+'</small><h3>'+escapeHtml(x.title)+'</h3><a href="../'+escapeHtml(x.page)+'" target="_blank">View article →</a></div>').join("");document.getElementById("newsList").innerHTML=data.slice(0,10).map(x=>'<div class="item"><small>'+x.date+' · '+x.category+'</small><h3>'+escapeHtml(x.title)+'</h3><a href="../'+escapeHtml(x.page)+'" target="_blank">Open →</a></div>').join("")}catch(e){}}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function route(){const id=location.hash.slice(1)||"overview";document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===id));document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+id));const link=document.querySelector('nav a[href="#'+id+'"]');document.getElementById("pageTitle").textContent=link?link.textContent.replace(/^\S+\s/,""):id;document.querySelector(".sidebar")?.classList.remove("open")}
async function boot(){const ok=await checkAuth();if(!ok)return;renderSources();await Promise.all([loadPublished(),loadStats()]);route()}
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("loginForm").addEventListener("submit",async e=>{e.preventDefault();const error=document.getElementById("loginError");error.textContent="Signing in...";try{const data=await fetch(WORKER_URL+"/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:document.getElementById("loginEmail").value,password:document.getElementById("loginPassword").value})});const result=await data.json();if(!data.ok)throw new Error(result.error||"Login failed");sessionStorage.setItem("techpulse_admin_session",result.token);document.getElementById("loginPassword").value="";error.textContent="";await boot()}catch(err){error.textContent=err.message}});document.getElementById("menu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");document.getElementById("refresh").onclick=loadPublished;document.getElementById("logout").onclick=async()=>{try{await api("/admin/logout",{method:"POST"})}catch(e){}sessionStorage.removeItem("techpulse_admin_session");showLogin(true)};window.addEventListener("hashchange",route);boot()});